'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace bizagiWebService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="bizagiWebService.WorkflowEngineSOASoap")>  _
    Public Interface WorkflowEngineSOASoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ping(ByVal sMessage As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function pingAsync(ByVal sMessage As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/createCasesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function createCasesAsString(ByVal casesInfo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/createCasesAsString", ReplyAction:="*")>  _
        Function createCasesAsStringAsync(ByVal casesInfo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/performActivityAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function performActivityAsString(ByVal activityInfo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/performActivityAsString", ReplyAction:="*")>  _
        Function performActivityAsStringAsync(ByVal activityInfo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/setEventAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setEventAsString(ByVal eventInfo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/setEventAsString", ReplyAction:="*")>  _
        Function setEventAsStringAsync(ByVal eventInfo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCasesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCasesAsString(ByVal caseFilters As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCasesAsString", ReplyAction:="*")>  _
        Function getCasesAsStringAsync(ByVal caseFilters As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/saveActivityAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function saveActivityAsString(ByVal activityInfo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/saveActivityAsString", ReplyAction:="*")>  _
        Function saveActivityAsStringAsync(ByVal activityInfo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getActivitiesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getActivitiesAsString(ByVal activityFilters As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getActivitiesAsString", ReplyAction:="*")>  _
        Function getActivitiesAsStringAsync(ByVal activityFilters As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/suspendCasesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function suspendCasesAsString(ByVal cases As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/suspendCasesAsString", ReplyAction:="*")>  _
        Function suspendCasesAsStringAsync(ByVal cases As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/resumeCasesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function resumeCasesAsString(ByVal cases As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/resumeCasesAsString", ReplyAction:="*")>  _
        Function resumeCasesAsStringAsync(ByVal cases As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getClosedActivitiesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getClosedActivitiesAsString(ByVal caseInfo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getClosedActivitiesAsString", ReplyAction:="*")>  _
        Function getClosedActivitiesAsStringAsync(ByVal caseInfo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEventsAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getEventsAsString(ByVal actFilters As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEventsAsString", ReplyAction:="*")>  _
        Function getEventsAsStringAsync(ByVal actFilters As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWorkflowClassesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getWorkflowClassesAsString(ByVal category As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWorkflowClassesAsString", ReplyAction:="*")>  _
        Function getWorkflowClassesAsStringAsync(ByVal category As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategoriesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCategoriesAsString(ByVal appName As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategoriesAsString", ReplyAction:="*")>  _
        Function getCategoriesAsStringAsync(ByVal appName As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/abortCasesAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function abortCasesAsString(ByVal info As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/abortCasesAsString", ReplyAction:="*")>  _
        Function abortCasesAsStringAsync(ByVal info As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getAssignationLogAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getAssignationLogAsString(ByVal info As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getAssignationLogAsString", ReplyAction:="*")>  _
        Function getAssignationLogAsStringAsync(ByVal info As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CheckPassword", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckPassword(ByVal sDomain As String, ByVal sUserName As String, ByVal sPassword As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CheckPassword", ReplyAction:="*")>  _
        Function CheckPasswordAsync(ByVal sDomain As String, ByVal sUserName As String, ByVal sPassword As String) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/assignActivityAsString", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function assignActivityAsString(ByVal info As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/assignActivityAsString", ReplyAction:="*")>  _
        Function assignActivityAsStringAsync(ByVal info As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/grantCaseAccess", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function grantCaseAccess(ByVal caseAccessXML As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/grantCaseAccess", ReplyAction:="*")>  _
        Function grantCaseAccessAsync(ByVal caseAccessXML As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/revokeCaseAccess", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function revokeCaseAccess(ByVal caseAccessXML As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/revokeCaseAccess", ReplyAction:="*")>  _
        Function revokeCaseAccessAsync(ByVal caseAccessXML As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/cleanTestData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function cleanTestData(ByVal caseInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/cleanTestData", ReplyAction:="*")>  _
        Function cleanTestDataAsync(ByVal caseInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/createCases", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function createCases(ByVal casesInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/createCases", ReplyAction:="*")>  _
        Function createCasesAsync(ByVal casesInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/evalRule", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function evalRule(ByVal assertionInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/evalRule", ReplyAction:="*")>  _
        Function evalRuleAsync(ByVal assertionInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getActivities", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getActivities(ByVal activitiesFilters As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getActivities", ReplyAction:="*")>  _
        Function getActivitiesAsync(ByVal activitiesFilters As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getAssignationLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getAssignationLog(ByVal caseInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getAssignationLog", ReplyAction:="*")>  _
        Function getAssignationLogAsync(ByVal caseInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getClosedActivities", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getClosedActivities(ByVal caseInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getClosedActivities", ReplyAction:="*")>  _
        Function getClosedActivitiesAsync(ByVal caseInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/performActivity", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function performActivity(ByVal activityInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/performActivity", ReplyAction:="*")>  _
        Function performActivityAsync(ByVal activityInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/resumeCases", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function resumeCases(ByVal cases As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/resumeCases", ReplyAction:="*")>  _
        Function resumeCasesAsync(ByVal cases As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/rollbackCase", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function rollbackCase(ByVal caseInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/rollbackCase", ReplyAction:="*")>  _
        Function rollbackCaseAsync(ByVal caseInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/setEvent", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setEvent(ByVal eventInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/setEvent", ReplyAction:="*")>  _
        Function setEventAsync(ByVal eventInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/suspendCases", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function suspendCases(ByVal cases As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/suspendCases", ReplyAction:="*")>  _
        Function suspendCasesAsync(ByVal cases As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/abortCases", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function abortCases(ByVal casesInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/abortCases", ReplyAction:="*")>  _
        Function abortCasesAsync(ByVal casesInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getApplications", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getApplications() As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getApplications", ReplyAction:="*")>  _
        Function getApplicationsAsync() As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategories", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCategories(ByVal application As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategories", ReplyAction:="*")>  _
        Function getCategoriesAsync(ByVal application As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategories2", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCategories2(ByVal applicationName As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategories2", ReplyAction:="*")>  _
        Function getCategories2Async(ByVal applicationName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategoriesFromApplicationName", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCategoriesFromApplicationName(ByVal applicationName As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategoriesFromApplicationName", ReplyAction:="*")>  _
        Function getCategoriesFromApplicationNameAsync(ByVal applicationName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWorkflowClassesFromCategoryName", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getWorkflowClassesFromCategoryName(ByVal categoryName As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWorkflowClassesFromCategoryName", ReplyAction:="*")>  _
        Function getWorkflowClassesFromCategoryNameAsync(ByVal categoryName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategoriesLocalized", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCategoriesLocalized(ByVal applicationName As String, ByVal cultureName As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCategoriesLocalized", ReplyAction:="*")>  _
        Function getCategoriesLocalizedAsync(ByVal applicationName As String, ByVal cultureName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWorkflowClasses", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getWorkflowClasses(ByVal category As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWorkflowClasses", ReplyAction:="*")>  _
        Function getWorkflowClassesAsync(ByVal category As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWorkflowClasses2", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getWorkflowClasses2(ByVal categoryName As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWorkflowClasses2", ReplyAction:="*")>  _
        Function getWorkflowClasses2Async(ByVal categoryName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEvents", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getEvents(ByVal activitiesFilters As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getEvents", ReplyAction:="*")>  _
        Function getEventsAsync(ByVal activitiesFilters As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCases", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCases(ByVal casesFilters As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getCases", ReplyAction:="*")>  _
        Function getCasesAsync(ByVal casesFilters As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/saveActivity", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function saveActivity(ByVal activityInfo As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/saveActivity", ReplyAction:="*")>  _
        Function saveActivityAsync(ByVal activityInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/assignActivity", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function assignActivity(ByVal xmlDoc As System.Xml.XmlNode) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/assignActivity", ReplyAction:="*")>  _
        Function assignActivityAsync(ByVal xmlDoc As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WorkflowEngineSOASoapChannel
        Inherits bizagiWebService.WorkflowEngineSOASoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WorkflowEngineSOASoapClient
        Inherits System.ServiceModel.ClientBase(Of bizagiWebService.WorkflowEngineSOASoap)
        Implements bizagiWebService.WorkflowEngineSOASoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ping(ByVal sMessage As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.ping
            Return MyBase.Channel.ping(sMessage)
        End Function
        
        Public Function pingAsync(ByVal sMessage As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.pingAsync
            Return MyBase.Channel.pingAsync(sMessage)
        End Function
        
        Public Function createCasesAsString(ByVal casesInfo As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.createCasesAsString
            Return MyBase.Channel.createCasesAsString(casesInfo)
        End Function
        
        Public Function createCasesAsStringAsync(ByVal casesInfo As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.createCasesAsStringAsync
            Return MyBase.Channel.createCasesAsStringAsync(casesInfo)
        End Function
        
        Public Function performActivityAsString(ByVal activityInfo As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.performActivityAsString
            Return MyBase.Channel.performActivityAsString(activityInfo)
        End Function
        
        Public Function performActivityAsStringAsync(ByVal activityInfo As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.performActivityAsStringAsync
            Return MyBase.Channel.performActivityAsStringAsync(activityInfo)
        End Function
        
        Public Function setEventAsString(ByVal eventInfo As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.setEventAsString
            Return MyBase.Channel.setEventAsString(eventInfo)
        End Function
        
        Public Function setEventAsStringAsync(ByVal eventInfo As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.setEventAsStringAsync
            Return MyBase.Channel.setEventAsStringAsync(eventInfo)
        End Function
        
        Public Function getCasesAsString(ByVal caseFilters As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.getCasesAsString
            Return MyBase.Channel.getCasesAsString(caseFilters)
        End Function
        
        Public Function getCasesAsStringAsync(ByVal caseFilters As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.getCasesAsStringAsync
            Return MyBase.Channel.getCasesAsStringAsync(caseFilters)
        End Function
        
        Public Function saveActivityAsString(ByVal activityInfo As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.saveActivityAsString
            Return MyBase.Channel.saveActivityAsString(activityInfo)
        End Function
        
        Public Function saveActivityAsStringAsync(ByVal activityInfo As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.saveActivityAsStringAsync
            Return MyBase.Channel.saveActivityAsStringAsync(activityInfo)
        End Function
        
        Public Function getActivitiesAsString(ByVal activityFilters As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.getActivitiesAsString
            Return MyBase.Channel.getActivitiesAsString(activityFilters)
        End Function
        
        Public Function getActivitiesAsStringAsync(ByVal activityFilters As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.getActivitiesAsStringAsync
            Return MyBase.Channel.getActivitiesAsStringAsync(activityFilters)
        End Function
        
        Public Function suspendCasesAsString(ByVal cases As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.suspendCasesAsString
            Return MyBase.Channel.suspendCasesAsString(cases)
        End Function
        
        Public Function suspendCasesAsStringAsync(ByVal cases As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.suspendCasesAsStringAsync
            Return MyBase.Channel.suspendCasesAsStringAsync(cases)
        End Function
        
        Public Function resumeCasesAsString(ByVal cases As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.resumeCasesAsString
            Return MyBase.Channel.resumeCasesAsString(cases)
        End Function
        
        Public Function resumeCasesAsStringAsync(ByVal cases As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.resumeCasesAsStringAsync
            Return MyBase.Channel.resumeCasesAsStringAsync(cases)
        End Function
        
        Public Function getClosedActivitiesAsString(ByVal caseInfo As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.getClosedActivitiesAsString
            Return MyBase.Channel.getClosedActivitiesAsString(caseInfo)
        End Function
        
        Public Function getClosedActivitiesAsStringAsync(ByVal caseInfo As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.getClosedActivitiesAsStringAsync
            Return MyBase.Channel.getClosedActivitiesAsStringAsync(caseInfo)
        End Function
        
        Public Function getEventsAsString(ByVal actFilters As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.getEventsAsString
            Return MyBase.Channel.getEventsAsString(actFilters)
        End Function
        
        Public Function getEventsAsStringAsync(ByVal actFilters As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.getEventsAsStringAsync
            Return MyBase.Channel.getEventsAsStringAsync(actFilters)
        End Function
        
        Public Function getWorkflowClassesAsString(ByVal category As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.getWorkflowClassesAsString
            Return MyBase.Channel.getWorkflowClassesAsString(category)
        End Function
        
        Public Function getWorkflowClassesAsStringAsync(ByVal category As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.getWorkflowClassesAsStringAsync
            Return MyBase.Channel.getWorkflowClassesAsStringAsync(category)
        End Function
        
        Public Function getCategoriesAsString(ByVal appName As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.getCategoriesAsString
            Return MyBase.Channel.getCategoriesAsString(appName)
        End Function
        
        Public Function getCategoriesAsStringAsync(ByVal appName As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.getCategoriesAsStringAsync
            Return MyBase.Channel.getCategoriesAsStringAsync(appName)
        End Function
        
        Public Function abortCasesAsString(ByVal info As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.abortCasesAsString
            Return MyBase.Channel.abortCasesAsString(info)
        End Function
        
        Public Function abortCasesAsStringAsync(ByVal info As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.abortCasesAsStringAsync
            Return MyBase.Channel.abortCasesAsStringAsync(info)
        End Function
        
        Public Function getAssignationLogAsString(ByVal info As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.getAssignationLogAsString
            Return MyBase.Channel.getAssignationLogAsString(info)
        End Function
        
        Public Function getAssignationLogAsStringAsync(ByVal info As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.getAssignationLogAsStringAsync
            Return MyBase.Channel.getAssignationLogAsStringAsync(info)
        End Function
        
        Public Function CheckPassword(ByVal sDomain As String, ByVal sUserName As String, ByVal sPassword As String) As Integer Implements bizagiWebService.WorkflowEngineSOASoap.CheckPassword
            Return MyBase.Channel.CheckPassword(sDomain, sUserName, sPassword)
        End Function
        
        Public Function CheckPasswordAsync(ByVal sDomain As String, ByVal sUserName As String, ByVal sPassword As String) As System.Threading.Tasks.Task(Of Integer) Implements bizagiWebService.WorkflowEngineSOASoap.CheckPasswordAsync
            Return MyBase.Channel.CheckPasswordAsync(sDomain, sUserName, sPassword)
        End Function
        
        Public Function assignActivityAsString(ByVal info As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.assignActivityAsString
            Return MyBase.Channel.assignActivityAsString(info)
        End Function
        
        Public Function assignActivityAsStringAsync(ByVal info As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.assignActivityAsStringAsync
            Return MyBase.Channel.assignActivityAsStringAsync(info)
        End Function
        
        Public Function grantCaseAccess(ByVal caseAccessXML As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.grantCaseAccess
            Return MyBase.Channel.grantCaseAccess(caseAccessXML)
        End Function
        
        Public Function grantCaseAccessAsync(ByVal caseAccessXML As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.grantCaseAccessAsync
            Return MyBase.Channel.grantCaseAccessAsync(caseAccessXML)
        End Function
        
        Public Function revokeCaseAccess(ByVal caseAccessXML As String) As String Implements bizagiWebService.WorkflowEngineSOASoap.revokeCaseAccess
            Return MyBase.Channel.revokeCaseAccess(caseAccessXML)
        End Function
        
        Public Function revokeCaseAccessAsync(ByVal caseAccessXML As String) As System.Threading.Tasks.Task(Of String) Implements bizagiWebService.WorkflowEngineSOASoap.revokeCaseAccessAsync
            Return MyBase.Channel.revokeCaseAccessAsync(caseAccessXML)
        End Function
        
        Public Function cleanTestData(ByVal caseInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.cleanTestData
            Return MyBase.Channel.cleanTestData(caseInfo)
        End Function
        
        Public Function cleanTestDataAsync(ByVal caseInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.cleanTestDataAsync
            Return MyBase.Channel.cleanTestDataAsync(caseInfo)
        End Function
        
        Public Function createCases(ByVal casesInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.createCases
            Return MyBase.Channel.createCases(casesInfo)
        End Function
        
        Public Function createCasesAsync(ByVal casesInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.createCasesAsync
            Return MyBase.Channel.createCasesAsync(casesInfo)
        End Function
        
        Public Function evalRule(ByVal assertionInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.evalRule
            Return MyBase.Channel.evalRule(assertionInfo)
        End Function
        
        Public Function evalRuleAsync(ByVal assertionInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.evalRuleAsync
            Return MyBase.Channel.evalRuleAsync(assertionInfo)
        End Function
        
        Public Function getActivities(ByVal activitiesFilters As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getActivities
            Return MyBase.Channel.getActivities(activitiesFilters)
        End Function
        
        Public Function getActivitiesAsync(ByVal activitiesFilters As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getActivitiesAsync
            Return MyBase.Channel.getActivitiesAsync(activitiesFilters)
        End Function
        
        Public Function getAssignationLog(ByVal caseInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getAssignationLog
            Return MyBase.Channel.getAssignationLog(caseInfo)
        End Function
        
        Public Function getAssignationLogAsync(ByVal caseInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getAssignationLogAsync
            Return MyBase.Channel.getAssignationLogAsync(caseInfo)
        End Function
        
        Public Function getClosedActivities(ByVal caseInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getClosedActivities
            Return MyBase.Channel.getClosedActivities(caseInfo)
        End Function
        
        Public Function getClosedActivitiesAsync(ByVal caseInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getClosedActivitiesAsync
            Return MyBase.Channel.getClosedActivitiesAsync(caseInfo)
        End Function
        
        Public Function performActivity(ByVal activityInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.performActivity
            Return MyBase.Channel.performActivity(activityInfo)
        End Function
        
        Public Function performActivityAsync(ByVal activityInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.performActivityAsync
            Return MyBase.Channel.performActivityAsync(activityInfo)
        End Function
        
        Public Function resumeCases(ByVal cases As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.resumeCases
            Return MyBase.Channel.resumeCases(cases)
        End Function
        
        Public Function resumeCasesAsync(ByVal cases As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.resumeCasesAsync
            Return MyBase.Channel.resumeCasesAsync(cases)
        End Function
        
        Public Function rollbackCase(ByVal caseInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.rollbackCase
            Return MyBase.Channel.rollbackCase(caseInfo)
        End Function
        
        Public Function rollbackCaseAsync(ByVal caseInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.rollbackCaseAsync
            Return MyBase.Channel.rollbackCaseAsync(caseInfo)
        End Function
        
        Public Function setEvent(ByVal eventInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.setEvent
            Return MyBase.Channel.setEvent(eventInfo)
        End Function
        
        Public Function setEventAsync(ByVal eventInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.setEventAsync
            Return MyBase.Channel.setEventAsync(eventInfo)
        End Function
        
        Public Function suspendCases(ByVal cases As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.suspendCases
            Return MyBase.Channel.suspendCases(cases)
        End Function
        
        Public Function suspendCasesAsync(ByVal cases As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.suspendCasesAsync
            Return MyBase.Channel.suspendCasesAsync(cases)
        End Function
        
        Public Function abortCases(ByVal casesInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.abortCases
            Return MyBase.Channel.abortCases(casesInfo)
        End Function
        
        Public Function abortCasesAsync(ByVal casesInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.abortCasesAsync
            Return MyBase.Channel.abortCasesAsync(casesInfo)
        End Function
        
        Public Function getApplications() As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getApplications
            Return MyBase.Channel.getApplications
        End Function
        
        Public Function getApplicationsAsync() As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getApplicationsAsync
            Return MyBase.Channel.getApplicationsAsync
        End Function
        
        Public Function getCategories(ByVal application As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getCategories
            Return MyBase.Channel.getCategories(application)
        End Function
        
        Public Function getCategoriesAsync(ByVal application As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getCategoriesAsync
            Return MyBase.Channel.getCategoriesAsync(application)
        End Function
        
        Public Function getCategories2(ByVal applicationName As String) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getCategories2
            Return MyBase.Channel.getCategories2(applicationName)
        End Function
        
        Public Function getCategories2Async(ByVal applicationName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getCategories2Async
            Return MyBase.Channel.getCategories2Async(applicationName)
        End Function
        
        Public Function getCategoriesFromApplicationName(ByVal applicationName As String) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getCategoriesFromApplicationName
            Return MyBase.Channel.getCategoriesFromApplicationName(applicationName)
        End Function
        
        Public Function getCategoriesFromApplicationNameAsync(ByVal applicationName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getCategoriesFromApplicationNameAsync
            Return MyBase.Channel.getCategoriesFromApplicationNameAsync(applicationName)
        End Function
        
        Public Function getWorkflowClassesFromCategoryName(ByVal categoryName As String) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getWorkflowClassesFromCategoryName
            Return MyBase.Channel.getWorkflowClassesFromCategoryName(categoryName)
        End Function
        
        Public Function getWorkflowClassesFromCategoryNameAsync(ByVal categoryName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getWorkflowClassesFromCategoryNameAsync
            Return MyBase.Channel.getWorkflowClassesFromCategoryNameAsync(categoryName)
        End Function
        
        Public Function getCategoriesLocalized(ByVal applicationName As String, ByVal cultureName As String) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getCategoriesLocalized
            Return MyBase.Channel.getCategoriesLocalized(applicationName, cultureName)
        End Function
        
        Public Function getCategoriesLocalizedAsync(ByVal applicationName As String, ByVal cultureName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getCategoriesLocalizedAsync
            Return MyBase.Channel.getCategoriesLocalizedAsync(applicationName, cultureName)
        End Function
        
        Public Function getWorkflowClasses(ByVal category As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getWorkflowClasses
            Return MyBase.Channel.getWorkflowClasses(category)
        End Function
        
        Public Function getWorkflowClassesAsync(ByVal category As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getWorkflowClassesAsync
            Return MyBase.Channel.getWorkflowClassesAsync(category)
        End Function
        
        Public Function getWorkflowClasses2(ByVal categoryName As String) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getWorkflowClasses2
            Return MyBase.Channel.getWorkflowClasses2(categoryName)
        End Function
        
        Public Function getWorkflowClasses2Async(ByVal categoryName As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getWorkflowClasses2Async
            Return MyBase.Channel.getWorkflowClasses2Async(categoryName)
        End Function
        
        Public Function getEvents(ByVal activitiesFilters As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getEvents
            Return MyBase.Channel.getEvents(activitiesFilters)
        End Function
        
        Public Function getEventsAsync(ByVal activitiesFilters As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getEventsAsync
            Return MyBase.Channel.getEventsAsync(activitiesFilters)
        End Function
        
        Public Function getCases(ByVal casesFilters As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.getCases
            Return MyBase.Channel.getCases(casesFilters)
        End Function
        
        Public Function getCasesAsync(ByVal casesFilters As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.getCasesAsync
            Return MyBase.Channel.getCasesAsync(casesFilters)
        End Function
        
        Public Function saveActivity(ByVal activityInfo As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.saveActivity
            Return MyBase.Channel.saveActivity(activityInfo)
        End Function
        
        Public Function saveActivityAsync(ByVal activityInfo As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.saveActivityAsync
            Return MyBase.Channel.saveActivityAsync(activityInfo)
        End Function
        
        Public Function assignActivity(ByVal xmlDoc As System.Xml.XmlNode) As System.Xml.XmlNode Implements bizagiWebService.WorkflowEngineSOASoap.assignActivity
            Return MyBase.Channel.assignActivity(xmlDoc)
        End Function
        
        Public Function assignActivityAsync(ByVal xmlDoc As System.Xml.XmlNode) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements bizagiWebService.WorkflowEngineSOASoap.assignActivityAsync
            Return MyBase.Channel.assignActivityAsync(xmlDoc)
        End Function
    End Class
End Namespace
